### PR TITLE
docs: :memo: clarify documentation cli boostrap command

### PR DESCRIPTION
**Pull request by DorianCBrwn**
Add which folder tto run  pnpm cli boostrap command to avoid errors

### CODE REVIEW

**Review by azrikahar — COMMENTED** [review]
Thanks for pointing this out! Maybe we can opt to only recommend `pnpm --dir api cli bootstrap` (so still running in the project root) which is the same as the current SQLite specific recommendation. We can then remove the SQLite caveat altogether.

**Comment by DorianCBrwn** [comment]
I agree I think that is a lot clearer. This is the first time I've tried setting up a large project like this and that would make things a lot easier to understand.

**Review by azrikahar — APPROVED** [review]
LGTM. Welcome aboard as a first-time contributor here 😊

**Review by br41nslug — APPROVED** [review]
Looks like a good improvement to prevent confusion thanks 😄 
In that same line of thinking we could also suggest `pnpm -F directus cli bootstrap` to keep it consistent with the dev commands 🤔

**Comment by azrikahar** [comment]
Very much agree on the consistency point! Was a bit conflicted as I sort of liked `--dir api` in terms of being more "readable" for users that are not yet familiar with pnpm. But yeah let's take this offline in our internal discussion to better gauge the general sentiment around this topic 👍

**Comment by rijkvanzanten** [comment]
Thanks @DorianCBrwn! And fun to see you around here 😄

**Pull request merged**
