### PR TITLE
layout media updated

### PR DESCRIPTION
**Pull request by erondpowell**

### CODE REVIEW

**Comment by erondpowell** [comment]
@br41nslug Do you mind checking over why header rules test is failing? I'm also curious if you find the answer.

The logs currently look like this:

Screenshot 2022-12-05 at 5 54 48 PM

**Comment by erondpowell** [comment]
@directus/team I'm not really sure why the headers failed for this PR, and when I open the logs, I get a *"spinning wheel of death"* with no actual log msg.... Could I get a friend to look over this and see if they can spot the issue?

**Comment by br41nslug** [comment]
@erondpowell The error is that it has found dead links
```
12:53:14 AM: - building client + server bundles...
12:53:15 AM: 
12:53:15 AM: (!) Found dead link /app/index in file /opt/build/repo/app/layouts.md
12:53:15 AM: If it is intended, you can use:
12:53:15 AM:     <a href="/app/index" target="_blank" rel="noreferrer">/app/index</a>
12:53:15 AM: 
12:53:15 AM: (!) Found dead link /app/index in file /opt/build/repo/app/layouts.md
12:53:15 AM: If it is intended, you can use:
12:53:15 AM:     <a href="/app/index" target="_blank" rel="noreferrer">/app/index</a>
12:53:26 AM: [vitepress] One or more pages contain dead links.
12:53:26 AM: ✖ building client + server bundles...
```

**Comment by erondpowell** [comment]
@br41nslug where did you find this log btw?

**Pull request merged**
