### PR TITLE
Clarifying multi-project usage in Reference documentation

### PR DESCRIPTION
**Pull request by adamjgrant**
For your consideration.

I found the instructions missing for configuring the frontend to show the multi project switcher: https://docs.directus.io/api/reference.html#projects-auth-config

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Thanks for the addition! I'm not too sure if it should go into the API reference though, as it's a setting specific to the application 🤔 

Also, the `allowOtherAPI` option renders an `Other...` option that allows the user to manually enter an API URL. It's not required for the dropdown to show up 🙂

**Comment by adamjgrant** [comment]
@rijkvanzanten Sure thing, I can edit this to put it in the right place.

As a user, though, it's not clear to me where to look. My goal here is to show users how to add multiple projects to their Suite install.

The website describes Directus as three components: App, API, and the Suite which combines the two.

Then the mental model hits a mismatch when I go to the [docs](https://docs.directus.io/getting-started/introduction.html). There is an "API Reference" but nothing that clearly maps to the App. The closest thing is to open up "Guides" and then "App User Guide," not at the same level as "API Reference."

In Guides > Projects, there's an area that tells you how to create a new project but it doesn't really show you. e.g. "Create a new API config file" What's that? "Add the API URL to your App config file" How? "Run the Directus Installer or manually setup" Wait, by now I've already run this, do I do it again or start over?

Above this is a link to "Learn how to connect to your different project APIs" and this takes us to the API Reference section. Clicking on this takes one to Project Prefix which describes how the project name in URLs works. Maybe this was supposed to redirect somewhere else?

**Comment by rijkvanzanten** [comment]
Very good point. Would it make sense to add a dedicated App section as well @adamjgrant? 

(@benhaynes 🔔)

**Comment by adamjgrant** [comment]
@rijkvanzanten Sure, and I'd be happy to help with that effort. Here's a napkin sketch of what that could look like.

This is meant to match more closely the IA of the directus.io homepage.

~~~
Current

- Getting Started
- Guides
- API Reference
- GraphQL
- SDKs
- Extensions
- Advanced

New

- Getting Started
  - [Existing child menu items]
  - Guides
- Directus Suite
  - Directus API
    - [Existing Child Menu items of API Reference]
  - Directus App 
    - [New docs, maybe some cherry picking or linking to stuff in the Guides section]
- Advanced
  - Extensions
  - SDKs
  - GraphQL
  - [Existing child menu items]
~~~

**Comment by benhaynes** [comment]
The main thing with VuePress (our docs generator) is how it nests the sections/pages/headings. For instance, we'll lose the deepest headings of API Reference if we move it into a nested section. I might recommend something like this:

```
Getting Started
Guides
  * GraphQL (move this here as one page)
  * Projects (I think this PR should live here)
App User Handbook (or Manual)
API Reference
SDKs
Extensions
Advanced
```

We have to be careful about how often we change this structure though, since it breaks all links (external and any hardcoded internal one) to those pages.

I think the `App User Guide` being top-level should give the App the priority it needs. The `Guides` are for both App and API, and are more conceptual.

Thoughts on this? We could try it out for a bit by changing the nav structure **without** changing the URL structure yet. That way we don't break anything until we know this is what we want.

**Comment by benhaynes** [comment]
As long as the Docs are organized properly, we can *link* to important pages elsewhere. Meaning that we can add links from the `API Reference` or `Getting Started` to the `Guides>Projects`.

**Comment by adamjgrant** [comment]
That works for me. I'll be back next week to give this a shot. BRB.

cc @benhaynes @rijkvanzanten

**Comment by rijkvanzanten** [comment]
Just updated the API reference to include this information 🙂

**Pull request closed without merging**
