### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by moritzgvt**
-  Add additional link because we are in the process

### CODE REVIEW

**Review by br41nslug — APPROVED** [review]

**Comment by br41nslug** [comment]
Nice catch and thanks for the pr :)

**Comment by moritzgvt** [comment]
No problem! 👍

**Comment by moritzgvt** [comment]
I just found a bunch of more broken links … may I ask how you generate the docs? Are you writing it in plain md or do you use any kind of tool for technical writing? Seems like those links are mostly off about 1-2 directories.

**Comment by br41nslug** [comment]
These docs are not generated but indeed handwritten currently. I don't personally do the technical writing but @erondpowell can probably answer that. The upcoming refactor to vitepress however should catch these broken links in the build process https://github.com/directus/docs/pull/54 .

**Comment by erondpowell** [comment]
> I just found a bunch of more broken links … may I ask how you generate the docs? Are you writing it in plain md or do you use any kind of tool for technical writing? Seems like those links are mostly off about 1-2 directories.

As Brainslug mentioned, we are *(using Vuepress and)* moving to Vitepress.
Apologies on the broken link, lots and lots of docs updates lately.
Once we switch to VitePress, there's a broken-links checker built-in, so we should be broken link free forever! 😄 
That should very very soon. Here's the PR if you're interested in watching: https://github.com/directus/docs/pull/54

**Comment by moritzgvt** [comment]
Nice, thanks for the clarification! Looking forward using the new docs – keep up the great work! 🚀

**Pull request merged**
