### PR TITLE
Nested Sidebar

### LINKED ISSUE #108: Re-implement the nested sidebar.
Update vitepress and add the nested sidebar feature where relevant.

### PR DESCRIPTION
**Pull request by erondpowell**
Closes #108 
It was a very simple change.
Checked pretty carefully for any potential weirdness in the switch.
If it looks good to y'all, I feel confident we can merge it.

### CODE REVIEW

**Review by azrikahar — COMMENTED** [review]
Oddly it looks good in dev (`pnpm dev`), but when testing the prod build either using:

- the deploy preview link in this PR: https://deploy-preview-109--directus-docs.netlify.app/

- or test it locally via `pnpm build`, then `pnpm serve`

The sidebar will show quite a number of duplicates:

chrome_zbPJY5pQ3X

---

After referring to VitePress docs, a quick hypothesis I had was that nested items' parent cannot have a link, so I tried removing `link: '/configuration/data-model'` in line 265 and it works, no longer shows any duplicates 🤔

https://github.com/directus/docs/blob/1e3a302a3512be6eceae50f3dfa3a15a26f1d6df/.vitepress/config.js#L264-L285

but then that doesn't explain why Flows can still have a link in line 307 and works flawlessly (only after removing data-model's link):

https://github.com/directus/docs/blob/1e3a302a3512be6eceae50f3dfa3a15a26f1d6df/.vitepress/config.js#L306-L323

so it feels like a VitePress bug, at least with the current observations, especially since dev works fine.

**Comment by erondpowell** [comment]
Okay, good eye Azzy. I can report this to vitepress when I wakeup tomorrow. Thanks for checking it out!

**Comment by brc-dd** [comment]
> but then that doesn't explain why Flows can still have a link in line 307 and works flawlessly

It doesn't. There are still hydration errors (check console). You need to remove all such links (/self-hosted/installation, /app/content, /configuration/flows, /configuration/data-model).

**Comment by azrikahar** [comment]
> It doesn't. There are still hydration errors (check console). You need to remove all such links (/self-hosted/installation, /app/content, /configuration/flows, /configuration/data-model). Also, there is an empty object in list, remove that too.

Thanks for looking into this! Just to confirm, this meant the aforementioned links (or the way we're currently using them) are not a valid usage? Just wanted to be sure so that we'll need to move/restructure the pages in those links 👍

**Comment by brc-dd** [comment]
@azrikahar I've fixed that in VitePress. From next version you can use them. (Just remove empty sidebar items anyway.)

**Comment by azrikahar** [comment]
@brc-dd Thanks for clarifying 😊 Will do!

**Comment by br41nslug** [comment]
Im still seeing the duplicate items for `vitepress v1.0.0-alpha.13`  so we'll need a bit of patience for the fix to be released 😄

**Review by br41nslug — APPROVED** [review]
Works as expected with the vitepress update 🎉

**Comment by rijkvanzanten** [comment]
@erondpowell @br41nslug seems like this doesn't fully works as expected. Every sidebar menu has random `#` appended now:
CleanShot 2022-09-14 at 16 06 43@2x

**Comment by erondpowell** [comment]
Did you revert this already? I couldn't identify a PR doing so.
And this hasn't happened on my Macbook pro all day.
Is it still happening?

https://user-images.githubusercontent.com/62306630/190302330-a00d9897-a105-4ec6-bda3-34eefab3bd33.mov

**Comment by brc-dd** [comment]
@rijkvanzanten If it's still happening for you can you tell your browser and OS version? We changed certain stuff in VitePress to make the outline dynamic and that trailing `#` maybe a bug.

**Comment by br41nslug** [comment]
Can't say i've seen that specific bug during my chrome/firefox tests :(

**Comment by brc-dd** [comment]
Yeah it's happening on Safari (15.3) for me. Rest of the browsers are fine.

**Comment by brc-dd** [comment]
Upgrade your VitePress version. It should be fixed now.

**Comment by rijkvanzanten** [comment]
> Yeah it's happening on Safari (15.3) for me. Rest of the browsers are fine.

Safari is my daily driver so that checks :)

**Pull request merged**
