### PR TITLE
Add environment variables for Flows

### PR DESCRIPTION
**Pull request by licitdev**
Ref: https://github.com/directus/directus/pull/16111

### CODE REVIEW

**Comment by br41nslug** [comment]
I believe an extra mention of how to access the allowed Environment variables would be useful to people. I spent some time looking through the "flows object" realizing it wasnt there before trying the nodejs way `process.env.VAR` 🤦 perhaps a small example could prevent other people from falling for the same.

**Comment by licitdev** [comment]
@br41nslug Great suggestion, just added it in! Thanks~ 😄  
CC @erondpowell

image

**Comment by rijkvanzanten** [comment]
Alternatively, we could also make them available through `$env` to keep it consistent in the data chain? 🤔

**Comment by licitdev** [comment]
> Alternatively, we could also make them available through `$env` to keep it consistent in the data chain? 🤔

Great suggestion! 👍 Adding the `$env` does feel more consistent in the data chain. 
A similar addition should also be done in a separate PR for `$last` and `$trigger`.

image

**Pull request merged**
