### PR TITLE
[docs] add tip on loading extensions within docker.

### PR DESCRIPTION
**Pull request by that1matt**
When loading custom extensions in docker, you get a warning message if the extension entry point is not `src/index.js`. Changing the `package.json` value for `directus:extension.path` from `dist/index.js` to `index.js` resolves the warning and loads the extension in the docker container following all other recommended folder structures.

This happens with the `npm init directus-extension` command using both `typescript` & `javascript`.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
How are you adding the extension to your docker image when you're getting this error?

**Comment by that1matt** [comment]
> 

I am just using the `volumes:` in my docker-compose.yml as described in the [directus docs](https://docs.directus.io/self-hosted/installation/docker.html).

```yaml
 volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
```

Then running through [creating extensions documentation](https://docs.directus.io/extensions/creating-extensions.html).

Without changing the path, the extension never loads.

**Comment by azrikahar** [comment]
When creating an extension, it should be created outside of `/directus/extensions` and only the built `index.js` should be included such as `directus/extensions/<extension-type>/<name-of-your-extension>/index.js`.

For example (slightly simplified tree):

```
├── my-custom-endpoint/
│   ├── src/
│   └── package.json
└── directus/
    ├── extensions/
    └── docker-compose.yml
```

The path for `my-custom-endpoint` to place the built `index.js` file from _it's own directory_ would be `../directus/extensions/endpoints/my-custom-endpoint/index.js`. The `extensions` directory should contain only the `index.js` file for all of the extensions rather than the whole scaffolded project 👍

**Comment by rijkvanzanten** [comment]
Thanks for clarifying that @azrikahar. I thought that might've been what was going on here. Lets not change that workflow between docker and outside of docker. We can tweak the language around what needs to go in the extensions folder, but the suggestion to change the path in package.json kinda goes against the current intended extensions workflow 👍🏻

**Pull request closed without merging**
