### PR TITLE
Add spellchecker

### LINKED ISSUE #46: VitePress: Spellchecker CI
> Maybe we can also explore [spellchecker-cli](https://www.npmjs.com/package/spellchecker-cli) as a git hook or github action. 🤔
> It was what I used when I made the PR https://github.com/directus/directus/pull/9553. It may be non-trivial to setup a dictionary at first (to "whitelist" words such as Directus, O2M, M2A etc), however the bright side is that'll come with the advantage of standardizing the letter casing for words/terms that have been discussed for a while.

@azrikahar I'm not sure if you want to work on this or just suggesting but I tagged you as an assignee.

### PR DESCRIPTION
**Pull request by azrikahar**
Closes #46

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by erondpowell** [comment]
@rijkvanzanten This is p much "ready"... There are 3 errors, left, but they have to do with the spellchecker being incorrect.

**Comment by rijkvanzanten** [comment]
I think 2 of those are problems to be fixed:
- `a` instead of `an`
- `webhook.`not being in the dictionary

The "double edit" is interesting, as it's caused by the icon use + word `edit`: `<span>edit</span> edit` which is a false positive 🤔 Not sure how to get around that though!

**Comment by rijkvanzanten** [comment]
Hack yet effective fix for the double "edit", just update it to.. `update` 😅

**Comment by erondpowell** [comment]
> I think 2 of those are problems to be fixed:
> 
> * `a` instead of `an`
> * `webhook.`not being in the dictionary
> 
> The "double edit" is interesting, as it's caused by the icon use + word `edit`: `<span>edit</span> edit` which is a false positive 🤔 Not sure how to get around that though!

 I'm 99.999% sure that grammar flag is wrong... it IS supposed to be "an npx".

**Comment by rijkvanzanten** [comment]
> it is supposed to be "an npx".

`npx` and `commands` are both not staring with vowel like sounds right? So should be `a` instead of `an`?

**Comment by erondpowell** [comment]
> `npx` and `commands` are both not staring with vowel-like sounds right? So should be `a` instead of `an`?
@rijkvanzanten 

vowel-like sounds use "an" :
an apple
an orange
an O
an N (pronounced "an in")
an npx command

consonant words use "a":
a node-module (pronounced n)
a command

**Pull request merged**
