### PR TITLE
Add sidebar link for operations under extensions

### PR DESCRIPTION
**Pull request by azrikahar**
It was originally added in #36 but for VuePress, so this PR re-adds it for the current VitePress.

### CODE REVIEW

**Review by nickrum — APPROVED** [review]

**Comment by nickrum** [comment]
Just out of curiosity, why are there so many commented out `// type: 'page',` lines? 👀

**Comment by azrikahar** [comment]
> Just out of curiosity, why are there so many commented out `// type: 'page',` lines? 👀

I'm curious as well, but I assume it was used for VuePress, which was then copied directly and temporarily commented out to expedite the move to VitePress 👀 I do think that we should clean it up if it's not intentionally kept for reasons I'm not aware of.

**Comment by rijkvanzanten** [comment]
> Just out of curiosity, why are there so many commented out `// type: 'page',` lines? 👀

@erondpowell thoughts?

**Comment by erondpowell** [comment]
This was a relic from vuepress. There was reason to believe it might come back into play in the future.
(IIRC to enable us to add our own dividers in the sidebar).
I can delete these, as we wont even need to use the custom divider thing moving forward.

**Pull request merged**
