### PR TITLE
Add documentation for create relational data

### LINKED ISSUE #84: Add endpoint example accessing data
Add an example of a custom endpoint accessing data from collections

### PR DESCRIPTION
**Pull request by bjgajjar**
Add an example for adding data with below relations.

- O2M
- M2O
- M2M

### CODE REVIEW

**Comment by benhaynes** [comment]
Haha, whoops... just saw this. Thank you!!

**Comment by rijkvanzanten** [comment]
@bjgajjar Can you also add some docs on the `$delete` flag? 🙂

**Comment by bjgajjar** [comment]
@rijkvanzanten 

> add some docs on the `$delete` flag

Added that. Kindly have a look and provide your feedback :)

**Comment by rijkvanzanten** [comment]
LGTM!

**Pull request merged**
