### PR TITLE
Links from thumbnails

### PR DESCRIPTION
**Pull request by lrkwz**
Clicking thumbnails does not lead to full image

### CODE REVIEW

**Comment by benhaynes** [comment]
I had tried this, but for some reason VuePress was not parsing the links correctly. I was thinking about using `@vuepress/plugin-medium-zoom` for these... @rijkvanzanten thoughts?

**Comment by rijkvanzanten** [comment]
It would be nice if we could use a plugin that does it automagically for all images, so we don’t have to manually (remember) to add all the links

**Comment by rijkvanzanten** [comment]
@benhaynes that medium zoom one looks nice!

**Comment by benhaynes** [comment]
Yeah, it is nice... but I can't get it to work! 😞

**Comment by benhaynes** [comment]
I believe that @rijkvanzanten updated this manually — but thank you very much for the PR!

**Pull request closed without merging**
