### PR TITLE
Updated `app > content`

### PR DESCRIPTION
**Pull request by erondpowell**
Closes https://github.com/directus/docs/issues/71, closes https://github.com/directus/docs/issues/70

### CODE REVIEW

**Comment by erondpowell** [comment]
Reviewers: if you don't spot anything I overlooked here, feel free to merge!

**Review by br41nslug — CHANGES_REQUESTED** [review]
LGTM! But just one performance thing... All videos on these pages start auto playing, about 15 at the same time for the collections page, which really hurts my dev PC so i can't imagine phones appreciate that.
image

I think either removing the auto play or adding some logic so only the video in view is playing should solve this

**Review by azrikahar — APPROVED** [review]
LGTM as well 👍

@br41nslug brought up a great point regarding performance. Did a quick rough test by running the following snippet in browser devtools:

```js
const videos = document.querySelectorAll("video");

const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
        if (!entry.isIntersecting) {
            entry.target.pause();
        } else {
            entry.target.play();
        }
    });
}, { threshold: 1 });

for (const video of Array.from(videos)) {
    observer.observe(video);
}
```

The threshold can definitely be tweaked, but with value `1` (it must be fully in view to play), I am getting seeing the following result in Performance Monitor in Chrome devtools:

- Before

   mpc-be64_Ce73Bc5eTA

- After

   mpc-be64_NDHuGCtxAM

Seems like at least it has dips now since it's pausing other videos, so should be better? Not sure what would be a better way to gather empirical data here 😅

**Comment by rijkvanzanten** [comment]
Interesting @azrikahar @br41nslug, you'd expect browsers to be better at GPU management for inline playing vids that aren't actually being displayed. Adding a bit of JS to automagically stop those vids when they're outside of the viewport makes sense to me, though we have to be careful with re-registering those observers on page transitions (as the docs website is effectively a SPA)

**Comment by erondpowell** [comment]
@rijkvanzanten It seems this PR was halted due to the video playback thing, which is a separate issue I think.
Can we go ahead and merge this and count on the video optimization to be fixed when issue #100 gets closed?

**Comment by rijkvanzanten** [comment]
@erondpowell Yeah! Lets merge this and circle back for optimizations later 👍🏻 No need to block this PR for that

**Pull request merged**
