### PR TITLE
Added Gifs

### PR DESCRIPTION
**Pull request by Nitwel**
Hey,
I thought adding gifs at some places would be a nice thing to have.
Tell me if something should be changed or what you thing of it in general.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Ohh I like this!

We should consider using `<video>` elements with `.mp4` files with a fallback to .gif to improve performance and image quality though 🙂

**Comment by benhaynes** [comment]
Whoa — amazing idea!

Is it just me or is there a weird ghosting on [some of these](https://raw.githubusercontent.com/directus/docs/d2f50bd8beb67125ac0c8fdfb609f77d675af390/img/screenshots/filtering.gif)?

**Comment by rijkvanzanten** [comment]
Pretty sure that's the gif compression

**Comment by Nitwel** [comment]
Hmm, yep it seems so.

**Comment by Nitwel** [comment]
So what do you think:

- Should I create more gifs and they will be implemented as gifs 

or

- should I look into creating Videos (MP4) which will be implemented.

Also any other suggestions for Videos which you would like to see?

**Comment by rijkvanzanten** [comment]
I vote MP4! These initial ones would already be perfect 😄 

@benhaynes any thoughts on other useful example videos?

**Comment by benhaynes** [comment]
I vote MP4 too... other possibilities include: Install Flow and any other guides (eg: relational)... we can always add more later. :)

**Comment by benhaynes** [comment]
And maybe we can add some info on the video sizing, format, and template tracked so others can add more?

**Comment by Nitwel** [comment]
I recorded the few Videos in 1920 by 1080 (20 fps).

**Comment by Nitwel** [comment]
and how do you implemend videos then?

**Comment by Nitwel** [comment]
Videos are now mp4 ^^.

**Comment by benhaynes** [comment]
Awesome! We're a bit slow this week since our API Lead is leaving... but we'll review and merge this asap!

**Comment by rijkvanzanten** [comment]
Let's make them autoplay, so they behave a little bit more as a gif 🙂 

Now: 

```html
<video width="100%" controls>
```

Proposed change:

```html
<video width="100%" autoplay muted>
```

(`muted` makes sure the browser allows autoplay)

**Comment by Nitwel** [comment]
The tags for the video are now [autoplay, muted, control, loop].
I keept the controll attr. because the videos are hard to see when watching them in this small window.

**Pull request merged**
