### PR TITLE
Added error codes for 2fa + token error codes

### PR DESCRIPTION
**Pull request by OscBacon**
Related to PR: https://github.com/directus/api/pull/1031

Also added missing error codes for 109 and 110

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Are codes 109 and 110 really `500` internal server errors? Sounds like they should be `401`s.. @bjgajjar can we confirm this?

**Comment by OscBacon** [comment]
@rijkvanzanten Any update on this?

**Comment by rijkvanzanten** [comment]
@bjgajjar 🤷‍♂

**Comment by bjgajjar** [comment]
Hey @rijkvanzanten,

Yes, that's correct. 109 and 110 throws `500` error.

**Comment by OscBacon** [comment]
Good to merge then?

**Comment by rijkvanzanten** [comment]
@OscBacon this looks all good to me 👍 Lets wait until https://github.com/directus/api/pull/1031 is merged in, so we don't promise things in the docs that don't exist (yet) 🙂

**Comment by rijkvanzanten** [comment]
@bjgajjar I've added an issue regarding the 500 for errors 109 and 110: https://github.com/directus/api/issues/1054

**Comment by OscBacon** [comment]
Sounds good @rijkvanzanten :)

**Comment by bjgajjar** [comment]
Yes, Its already added in API and merged too :)

**Comment by rijkvanzanten** [comment]
@bjgajjar I meant the docs PR. There is a merge conflict in this PR because you already used code 109 for something else.

**Comment by bjgajjar** [comment]
@rijkvanzanten 

Oh! Yeah. I added 109 for `Auth validation error (422) - Invalid Email / Invalid Password`
So I think we should increase the code's value with 1 in this PR 

- `0110` - Invalid Request Token (500)
- `0111` - Expired Request Token (500)
- `0112` - User Missing 2FA OTP (404)
- `0113` - Invalid User OTP (404)
- `0114` - 2FA Enforced but Not Activated (401)

Hope it'll work :)

**Pull request merged**
