### PR TITLE
add default values to storage section to fix #106

### LINKED ISSUE #106: docs: document default storage path
The default storage path for the local adapter should be documented somewhere, probably in https://github.com/directus/docs/blob/master/advanced/api/configuration.md#storage at the field `root`.

I had to search way too long for this, I ended up checking directus/docker and found out the path is `/var/www/html/public/uploads/_/`.

I can send a PR if approved.

### PR DESCRIPTION
**Pull request by steebchen**

### CODE REVIEW

**Comment by steebchen** [comment]
Hmm, good question. It's definitely relative but I also have no idea where /var/www/html is defined, maybe somewhere in directus/docker?

**Comment by rijkvanzanten** [comment]
Ah, that sounds plausible, yeah!

**Comment by benhaynes** [comment]
Thank you @steebchen! 😄 

@rijkvanzanten do we need to ask the Docker guys about this or is it good to go?

**Comment by rijkvanzanten** [comment]
Let's change it to say the relative path so it matches the behavior on non-docker as well :+1:

**Comment by steebchen** [comment]
Ok but I'd still like to give a hint about the other path somewhere, because I still would't know where to look for files if I just knew the relative path :P

**Comment by rijkvanzanten** [comment]
Maybe that can be solved by adding the default location information to the readme of the Docker repo?

**Comment by steebchen** [comment]
Sounds good. I used relative paths in this PR now and squashed the commits

**Pull request merged**
